# ADD snippet directory
# Specify the snippet directory that is used by your VS code, something like: C:\Users\giuli\.vscode\extensions\tarasov-lab.phenoscript-0.0.14\snippets\
# Depending on your system it is located in:
#   Win: `%USERPROFILE%\.vscode\extensions`
#   Mac:`$HOME/.vscode/extensions`
#   Linux: `$HOME/.vscode/extensions`
snippet-dir: ~/.vscode/extensions/tarasov-lab.phenoscript-0.0.16/snippets
# ADD the names of the authors and ORCID
authors:
  'Giulio Montanaro': https://orcid.org/0000-0003-0836-1364
  'Sergei Tarasov': https://orcid.org/0000-0001-5237-2330
# ADD a short title of your project
project-title: "Testing Phenoscript Language: four species of Grebennikovius (Coleoptera: Scarabaeinae) from the Eastern Arc Mountains"
importOntologies:
  - https://raw.githubusercontent.com/sergeitarasov/aism/devel/src/ontology/aism-edit.owl
  - https://raw.githubusercontent.com/sergeitarasov/colao/devel/src/ontology/colao-edit.owl
  - https://raw.githubusercontent.com/sergeitarasov/PhenoScript/main/phenospy_package/phenospy/package-data/phenoscript.owl
  - http://purl.obolibrary.org/obo/pato.owl
  - http://purl.obolibrary.org/obo/bspo.owl
  - http://purl.obolibrary.org/obo/cdao.owl
  - http://purl.obolibrary.org/obo/iao.owl
  - http://purl.obolibrary.org/obo/ro.owl
  - http://purl.obolibrary.org/obo/uo.owl
  - http://purl.obolibrary.org/obo/bco.owl
  - http://purl.obolibrary.org/obo/uberon/uberon-base.owl
  - http://purl.obolibrary.org/obo/taxrank.owl
namespace:
  default:    http://www.w3.org/2002/07/owl#
  others:
    rdfs:     http://www.w3.org/2000/01/rdf-schema#
    formats:  http://www.geneontology.org/formats/oboInOwl#
    dc:       http://purl.org/dc/
    hao:      http://purl.obolibrary.org/obo/HAO_
    aism:     http://purl.obolibrary.org/obo/AISM_
    colao:    http://purl.obolibrary.org/obo/COLAO_
    bfo:      http://purl.obolibrary.org/obo/BFO_
    ro:       http://purl.obolibrary.org/obo/RO_
    obi:      http://purl.obolibrary.org/obo/OBI_
    ncbi:     http://purl.obolibrary.org/obo/NCBITaxon_
    iao:      http://purl.obolibrary.org/obo/IAO_
    bspo:     http://purl.obolibrary.org/obo/BSPO_
    pato:     http://purl.obolibrary.org/obo/PATO_
    pato2:    http://purl.obolibrary.org/obo/pato#
    caro:     http://purl.obolibrary.org/obo/CARO_
    cdao:     http://purl.obolibrary.org/obo/CDAO_
    unit:     http://purl.obolibrary.org/obo/UO_
    dsw:      http://purl.org/dsw/
    dwc:      http://rs.tdwg.org/dwc/terms/
    zoo:      http://zoobank.org/
    gbif:     https://www.gbif.org/species/
    phs:      https://github.com/sergeitarasov/PhenoScript/PHS_
    uberon:   http://purl.obolibrary.org/obo/UBERON_
    taxrank:  http://purl.obolibrary.org/obo/TAXRANK_
    # obo: http://purl.obolibrary.org/obo/
